-- Bài 2
DROP DATABASE IF EXISTS Data_Type_1;
CREATE DATABASE Data_Type_1;
USE Data_Type_1;

CREATE TABLE Data_Type_1(
ID MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(50) NOT NULL,
`Code`  CHAR(50) UNIQUE NOT NULL,
Modified_Date DATETIME
);


